# Menggunakan base image yang ringan dan efisien
FROM node:18-alpine

# Menetapkan direktori kerja di dalam container
WORKDIR /app

# Salin package.json dan package-lock.json dari folder src
COPY src/package*.json ./

# Install semua dependencies
RUN npm install

# Salin sisa kode aplikasi dari folder src
COPY src/ .

# Buka port 3000 di container
EXPOSE 3000

# Perintah default untuk menjalankan aplikasi
# Ini akan menjalankan "node src/app.js" sesuai package.json
CMD ["npm", "start"]

# belum fix ini ternyata